# Generated by Django 3.1 on 2020-08-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='course_time_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email_id',
            field=models.EmailField(max_length=20),
        ),
    ]
