# Generated by Django 3.1 on 2020-08-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdemo', '0002_auto_20200828_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email_id',
            field=models.CharField(max_length=20),
        ),
    ]
