# Generated by Django 3.1 on 2020-08-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdemo', '0004_auto_20200828_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='child_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='course_time_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
    ]
